// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA2abs_INCLUDE_
#define _RA2abs_INCLUDE_
  #include "RA2prec.hpp"
  #include "RA2types.hpp"
  RA2floatS fabs(const RA2floatS& a);
  RA2floatD fabs(const RA2floatD& a);
#endif
