// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RA2abs.hpp"

RA2floatS fabs(const RA2floatS& a) {
  RA2floatS r;
  float factor_0;
  float factor_d;
  #include "RA2abs.ipp"
  return r;
}

RA2floatD fabs(const RA2floatD& a) {
  RA2floatD r;
  double factor_0;
  double factor_d;
  #include "RA2abs.ipp"
  return r;
}

