// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RA2acos.hpp"

RA2floatS acos(const RA2floatS& a) {
  RA2floatS r;
  RA2floatS h;
  RA2floatS t;
  #include "RA2acos.ipp"
  return r;
}

RA2floatD acos(const RA2floatD& a) {
  RA2floatD r;
  RA2floatD h;
  RA2floatD t;
  #include "RA2acos.ipp"
  return r;
}

