// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA2asin_INCLUDE_
#define _RA2asin_INCLUDE_
  #include "RA2prec.hpp"
  #include "RA2types.hpp"
  #include "RA2sqrt.hpp"
  #include "RA2div.hpp"
  #include "RA2mult.hpp"
  #include "RA2sub.hpp"
  RA2floatS asin(const RA2floatS& a);
  RA2floatD asin(const RA2floatD& a);
#endif
