// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
factor_0 = 0.0;
if (a.v != 0.0)
  {
    if (a.v < 0.0)
      {
        factor_0 = -1.0;
      }
    else
      {
        factor_0 = 1.0;
      }
  }
r.v = fabs(a.v);
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d1_1 != 0.0)
      {
        if (a.d1_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d1_1 = a.d1_1 * factor_d;
if (factor_d == 0.0)
  {
    if (a.d1_2 != 0.0)
      {
        if (a.d1_2 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d1_2 = a.d1_2 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d2_1 != 0.0)
      {
        if (a.d2_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d2_1 = a.d2_1 * factor_d;
if (factor_d == 0.0)
  {
    if (a.d2_2 != 0.0)
      {
        if (a.d2_2 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d2_2 = a.d2_2 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d3_1 != 0.0)
      {
        if (a.d3_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d3_1 = a.d3_1 * factor_d;
if (factor_d == 0.0)
  {
    if (a.d3_2 != 0.0)
      {
        if (a.d3_2 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d3_2 = a.d3_2 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d4_1 != 0.0)
      {
        if (a.d4_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d4_1 = a.d4_1 * factor_d;
if (factor_d == 0.0)
  {
    if (a.d4_2 != 0.0)
      {
        if (a.d4_2 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d4_2 = a.d4_2 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d5_1 != 0.0)
      {
        if (a.d5_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d5_1 = a.d5_1 * factor_d;
if (factor_d == 0.0)
  {
    if (a.d5_2 != 0.0)
      {
        if (a.d5_2 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d5_2 = a.d5_2 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d6_1 != 0.0)
      {
        if (a.d6_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d6_1 = a.d6_1 * factor_d;
if (factor_d == 0.0)
  {
    if (a.d6_2 != 0.0)
      {
        if (a.d6_2 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d6_2 = a.d6_2 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d7_1 != 0.0)
      {
        if (a.d7_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d7_1 = a.d7_1 * factor_d;
if (factor_d == 0.0)
  {
    if (a.d7_2 != 0.0)
      {
        if (a.d7_2 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d7_2 = a.d7_2 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d8_1 != 0.0)
      {
        if (a.d8_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d8_1 = a.d8_1 * factor_d;
if (factor_d == 0.0)
  {
    if (a.d8_2 != 0.0)
      {
        if (a.d8_2 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d8_2 = a.d8_2 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d9_1 != 0.0)
      {
        if (a.d9_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d9_1 = a.d9_1 * factor_d;
if (factor_d == 0.0)
  {
    if (a.d9_2 != 0.0)
      {
        if (a.d9_2 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d9_2 = a.d9_2 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d10_1 != 0.0)
      {
        if (a.d10_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d10_1 = a.d10_1 * factor_d;
if (factor_d == 0.0)
  {
    if (a.d10_2 != 0.0)
      {
        if (a.d10_2 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d10_2 = a.d10_2 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d11_1 != 0.0)
      {
        if (a.d11_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d11_1 = a.d11_1 * factor_d;
if (factor_d == 0.0)
  {
    if (a.d11_2 != 0.0)
      {
        if (a.d11_2 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d11_2 = a.d11_2 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d12_1 != 0.0)
      {
        if (a.d12_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d12_1 = a.d12_1 * factor_d;
if (factor_d == 0.0)
  {
    if (a.d12_2 != 0.0)
      {
        if (a.d12_2 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d12_2 = a.d12_2 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d13_1 != 0.0)
      {
        if (a.d13_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d13_1 = a.d13_1 * factor_d;
if (factor_d == 0.0)
  {
    if (a.d13_2 != 0.0)
      {
        if (a.d13_2 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d13_2 = a.d13_2 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d14_1 != 0.0)
      {
        if (a.d14_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d14_1 = a.d14_1 * factor_d;
if (factor_d == 0.0)
  {
    if (a.d14_2 != 0.0)
      {
        if (a.d14_2 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d14_2 = a.d14_2 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d15_1 != 0.0)
      {
        if (a.d15_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d15_1 = a.d15_1 * factor_d;
if (factor_d == 0.0)
  {
    if (a.d15_2 != 0.0)
      {
        if (a.d15_2 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d15_2 = a.d15_2 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d16_1 != 0.0)
      {
        if (a.d16_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d16_1 = a.d16_1 * factor_d;
if (factor_d == 0.0)
  {
    if (a.d16_2 != 0.0)
      {
        if (a.d16_2 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d16_2 = a.d16_2 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d17_1 != 0.0)
      {
        if (a.d17_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d17_1 = a.d17_1 * factor_d;
if (factor_d == 0.0)
  {
    if (a.d17_2 != 0.0)
      {
        if (a.d17_2 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d17_2 = a.d17_2 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d18_1 != 0.0)
      {
        if (a.d18_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d18_1 = a.d18_1 * factor_d;
if (factor_d == 0.0)
  {
    if (a.d18_2 != 0.0)
      {
        if (a.d18_2 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d18_2 = a.d18_2 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d19_1 != 0.0)
      {
        if (a.d19_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d19_1 = a.d19_1 * factor_d;
if (factor_d == 0.0)
  {
    if (a.d19_2 != 0.0)
      {
        if (a.d19_2 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d19_2 = a.d19_2 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d20_1 != 0.0)
      {
        if (a.d20_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d20_1 = a.d20_1 * factor_d;
if (factor_d == 0.0)
  {
    if (a.d20_2 != 0.0)
      {
        if (a.d20_2 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d20_2 = a.d20_2 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d21_1 != 0.0)
      {
        if (a.d21_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d21_1 = a.d21_1 * factor_d;
if (factor_d == 0.0)
  {
    if (a.d21_2 != 0.0)
      {
        if (a.d21_2 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d21_2 = a.d21_2 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d22_1 != 0.0)
      {
        if (a.d22_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d22_1 = a.d22_1 * factor_d;
if (factor_d == 0.0)
  {
    if (a.d22_2 != 0.0)
      {
        if (a.d22_2 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d22_2 = a.d22_2 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d23_1 != 0.0)
      {
        if (a.d23_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d23_1 = a.d23_1 * factor_d;
if (factor_d == 0.0)
  {
    if (a.d23_2 != 0.0)
      {
        if (a.d23_2 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d23_2 = a.d23_2 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d24_1 != 0.0)
      {
        if (a.d24_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d24_1 = a.d24_1 * factor_d;
if (factor_d == 0.0)
  {
    if (a.d24_2 != 0.0)
      {
        if (a.d24_2 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d24_2 = a.d24_2 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d25_1 != 0.0)
      {
        if (a.d25_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d25_1 = a.d25_1 * factor_d;
if (factor_d == 0.0)
  {
    if (a.d25_2 != 0.0)
      {
        if (a.d25_2 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d25_2 = a.d25_2 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d26_1 != 0.0)
      {
        if (a.d26_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d26_1 = a.d26_1 * factor_d;
if (factor_d == 0.0)
  {
    if (a.d26_2 != 0.0)
      {
        if (a.d26_2 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d26_2 = a.d26_2 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d27_1 != 0.0)
      {
        if (a.d27_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d27_1 = a.d27_1 * factor_d;
if (factor_d == 0.0)
  {
    if (a.d27_2 != 0.0)
      {
        if (a.d27_2 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d27_2 = a.d27_2 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d28_1 != 0.0)
      {
        if (a.d28_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d28_1 = a.d28_1 * factor_d;
if (factor_d == 0.0)
  {
    if (a.d28_2 != 0.0)
      {
        if (a.d28_2 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d28_2 = a.d28_2 * factor_d;
