// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA2atan_INCLUDE_
#define _RA2atan_INCLUDE_
  #include "RA2prec.hpp"
  #include "RA2types.hpp"
  #include "RA2add.hpp"
  #include "RA2div.hpp"
  #include "RA2mult.hpp"
  RA2floatS atan(const RA2floatS& a);
  RA2floatD atan(const RA2floatD& a);
#endif
