// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA2cos_INCLUDE_
#define _RA2cos_INCLUDE_
  #include "RA2prec.hpp"
  #include "RA2types.hpp"
  RA2floatS cos(const RA2floatS& a);
  RA2floatD cos(const RA2floatD& a);
#endif
