// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA2cosh_INCLUDE_
#define _RA2cosh_INCLUDE_
  #include "RA2prec.hpp"
  #include "RA2types.hpp"
  RA2floatS cosh(const RA2floatS& a);
  RA2floatD cosh(const RA2floatD& a);
#endif
