// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RA2cosh.hpp"

RA2floatS cosh(const RA2floatS& a) {
  RA2floatS c;
  RA2floatS s;
  RA2floatS t;
  #include "RA2sinhcosh.ipp"
  return c;
}

RA2floatD cosh(const RA2floatD& a) {
  RA2floatD c;
  RA2floatD s;
  RA2floatD t;
  #include "RA2sinhcosh.ipp"
  return c;
}

