// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA2exp_INCLUDE_
#define _RA2exp_INCLUDE_
  #include "RA2prec.hpp"
  #include "RA2types.hpp"
  RA2floatS exp(const RA2floatS& a);
  RA2floatD exp(const RA2floatD& a);
#endif
