// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RA2eqadd.hpp"

void operator +=(RA2floatS& r, const RA2floatS& b) {
  #include "RA2eqaddAA.ipp"
}

void operator +=(RA2floatD& r, const RA2floatS& b) {
  #include "RA2eqaddAA.ipp"
}

void operator +=(RA2floatD& r, const RA2floatD& b) {
  #include "RA2eqaddAA.ipp"
}

void operator +=(RA2floatS& r, const int& b) {
  #include "RA2eqaddAP.ipp"
}

void operator +=(RA2floatS& r, const float& b) {
  #include "RA2eqaddAP.ipp"
}

void operator +=(RA2floatD& r, const int& b) {
  #include "RA2eqaddAP.ipp"
}

void operator +=(RA2floatD& r, const float& b) {
  #include "RA2eqaddAP.ipp"
}

void operator +=(RA2floatD& r, const double& b) {
  #include "RA2eqaddAP.ipp"
}

