// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RA2exp.hpp"

RA2floatS exp(const RA2floatS& a) {
  RA2floatS r;
  RA2floatS s;
  RA2floatS t;
  #include "RA2exp.ipp"
  return r;
}

RA2floatD exp(const RA2floatD& a) {
  RA2floatD r;
  RA2floatD s;
  RA2floatD t;
  #include "RA2exp.ipp"
  return r;
}

