// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RA2eqdiv.hpp"

void operator /=(RA2floatS& r, const RA2floatS& b) {
  RA2floatS a = r;
  float recip;
  #include "RA2eqdivAA.ipp"
}

void operator /=(RA2floatD& r, const RA2floatS& b) {
  RA2floatD a = r;
  double recip;
  #include "RA2eqdivAA.ipp"
}

void operator /=(RA2floatD& r, const RA2floatD& b) {
  RA2floatD a = r;
  double recip;
  #include "RA2eqdivAA.ipp"
}

void operator /=(RA2floatS& r, const int& b) {
  RA2floatS a = r;
  float recip;
  #include "RA2eqdivAP.ipp"
}

void operator /=(RA2floatS& r, const float& b) {
  RA2floatS a = r;
  float recip;
  #include "RA2eqdivAP.ipp"
}

void operator /=(RA2floatD& r, const int& b) {
  RA2floatD a = r;
  double recip;
  #include "RA2eqdivAP.ipp"
}

void operator /=(RA2floatD& r, const float& b) {
  RA2floatD a = r;
  double recip;
  #include "RA2eqdivAP.ipp"
}

void operator /=(RA2floatD& r, const double& b) {
  RA2floatD a = r;
  double recip;
  #include "RA2eqdivAP.ipp"
}

