// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA2eq_INCLUDE_
#define _RA2eq_INCLUDE_
  #include "RA2prec.hpp"
  #include "RA2types.hpp"
  bool operator ==(const RA2floatS& a, const RA2floatS& b);
  bool operator ==(const RA2floatS& a, const RA2floatD& b);
  bool operator ==(const RA2floatD& a, const RA2floatS& b);
  bool operator ==(const RA2floatD& a, const RA2floatD& b);
  bool operator ==(const RA2floatS& a, const int& b);
  bool operator ==(const RA2floatS& a, const float& b);
  bool operator ==(const RA2floatS& a, const double& b);
  bool operator ==(const RA2floatD& a, const int& b);
  bool operator ==(const RA2floatD& a, const float& b);
  bool operator ==(const RA2floatD& a, const double& b);
  bool operator ==(const int& a, const RA2floatS& b);
  bool operator ==(const int& a, const RA2floatD& b);
  bool operator ==(const float& a, const RA2floatS& b);
  bool operator ==(const float& a, const RA2floatD& b);
  bool operator ==(const double& a, const RA2floatS& b);
  bool operator ==(const double& a, const RA2floatD& b);
#endif
