// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA2eqsub_INCLUDE_
#define _RA2eqsub_INCLUDE_
  #include "RA2prec.hpp"
  #include "RA2types.hpp"
  void operator -=(RA2floatS& r, const RA2floatS& b);
  void operator -=(RA2floatD& r, const RA2floatS& b);
  void operator -=(RA2floatD& r, const RA2floatD& b);
  void operator -=(RA2floatS& r, const int& b);
  void operator -=(RA2floatS& r, const float& b);
  void operator -=(RA2floatD& r, const int& b);
  void operator -=(RA2floatD& r, const float& b);
  void operator -=(RA2floatD& r, const double& b);
#endif
