// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA2log_INCLUDE_
#define _RA2log_INCLUDE_
  #include "RA2prec.hpp"
  #include "RA2types.hpp"
  RA2floatS log(const RA2floatS& a);
  RA2floatD log(const RA2floatD& a);
#endif
