// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA2min_INCLUDE_
#define _RA2min_INCLUDE_
  #include "RA2prec.hpp"
  #include "RA2types.hpp"
  RA2floatS min(const RA2floatS& a, const RA2floatS& b);
  RA2floatD min(const RA2floatS& a, const RA2floatD& b);
  RA2floatD min(const RA2floatD& a, const RA2floatS& b);
  RA2floatD min(const RA2floatD& a, const RA2floatD& b);
  RA2floatS min(const RA2floatS& a, const int& b);
  RA2floatS min(const RA2floatS& a, const float& b);
  RA2floatD min(const RA2floatS& a, const double& b);
  RA2floatD min(const RA2floatD& a, const int& b);
  RA2floatD min(const RA2floatD& a, const float& b);
  RA2floatD min(const RA2floatD& a, const double& b);
  RA2floatS min(const int& a, const RA2floatS& b);
  RA2floatD min(const int& a, const RA2floatD& b);
  RA2floatS min(const float& a, const RA2floatS& b);
  RA2floatD min(const float& a, const RA2floatD& b);
  RA2floatD min(const double& a, const RA2floatS& b);
  RA2floatD min(const double& a, const RA2floatD& b);
#endif
