// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RA2min.hpp"

RA2floatS min(const RA2floatS& a, const RA2floatS& b) {
  RA2floatS r;
  #include "RA2minAA.ipp"
  return r;
}

RA2floatD min(const RA2floatS& a, const RA2floatD& b) {
  RA2floatD r;
  #include "RA2minAA.ipp"
  return r;
}

RA2floatD min(const RA2floatD& a, const RA2floatS& b) {
  RA2floatD r;
  #include "RA2minAA.ipp"
  return r;
}

RA2floatD min(const RA2floatD& a, const RA2floatD& b) {
  RA2floatD r;
  #include "RA2minAA.ipp"
  return r;
}

RA2floatS min(const RA2floatS& a, const int& b) {
  RA2floatS r;
  #include "RA2minAP.ipp"
  return r;
}

RA2floatS min(const RA2floatS& a, const float& b) {
  RA2floatS r;
  #include "RA2minAP.ipp"
  return r;
}

RA2floatD min(const RA2floatS& a, const double& b) {
  RA2floatD r;
  #include "RA2minAP.ipp"
  return r;
}

RA2floatD min(const RA2floatD& a, const int& b) {
  RA2floatD r;
  #include "RA2minAP.ipp"
  return r;
}

RA2floatD min(const RA2floatD& a, const float& b) {
  RA2floatD r;
  #include "RA2minAP.ipp"
  return r;
}

RA2floatD min(const RA2floatD& a, const double& b) {
  RA2floatD r;
  #include "RA2minAP.ipp"
  return r;
}

RA2floatS min(const int& a, const RA2floatS& b) {
  RA2floatS r;
  #include "RA2minPA.ipp"
  return r;
}

RA2floatD min(const int& a, const RA2floatD& b) {
  RA2floatD r;
  #include "RA2minPA.ipp"
  return r;
}

RA2floatS min(const float& a, const RA2floatS& b) {
  RA2floatS r;
  #include "RA2minPA.ipp"
  return r;
}

RA2floatD min(const float& a, const RA2floatD& b) {
  RA2floatD r;
  #include "RA2minPA.ipp"
  return r;
}

RA2floatD min(const double& a, const RA2floatS& b) {
  RA2floatD r;
  #include "RA2minPA.ipp"
  return r;
}

RA2floatD min(const double& a, const RA2floatD& b) {
  RA2floatD r;
  #include "RA2minPA.ipp"
  return r;
}

