// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RA2max.hpp"

RA2floatS max(const RA2floatS& a, const RA2floatS& b) {
  RA2floatS r;
  #include "RA2maxAA.ipp"
  return r;
}

RA2floatD max(const RA2floatS& a, const RA2floatD& b) {
  RA2floatD r;
  #include "RA2maxAA.ipp"
  return r;
}

RA2floatD max(const RA2floatD& a, const RA2floatS& b) {
  RA2floatD r;
  #include "RA2maxAA.ipp"
  return r;
}

RA2floatD max(const RA2floatD& a, const RA2floatD& b) {
  RA2floatD r;
  #include "RA2maxAA.ipp"
  return r;
}

RA2floatS max(const RA2floatS& a, const int& b) {
  RA2floatS r;
  #include "RA2maxAP.ipp"
  return r;
}

RA2floatS max(const RA2floatS& a, const float& b) {
  RA2floatS r;
  #include "RA2maxAP.ipp"
  return r;
}

RA2floatD max(const RA2floatS& a, const double& b) {
  RA2floatD r;
  #include "RA2maxAP.ipp"
  return r;
}

RA2floatD max(const RA2floatD& a, const int& b) {
  RA2floatD r;
  #include "RA2maxAP.ipp"
  return r;
}

RA2floatD max(const RA2floatD& a, const float& b) {
  RA2floatD r;
  #include "RA2maxAP.ipp"
  return r;
}

RA2floatD max(const RA2floatD& a, const double& b) {
  RA2floatD r;
  #include "RA2maxAP.ipp"
  return r;
}

RA2floatS max(const int& a, const RA2floatS& b) {
  RA2floatS r;
  #include "RA2maxPA.ipp"
  return r;
}

RA2floatD max(const int& a, const RA2floatD& b) {
  RA2floatD r;
  #include "RA2maxPA.ipp"
  return r;
}

RA2floatS max(const float& a, const RA2floatS& b) {
  RA2floatS r;
  #include "RA2maxPA.ipp"
  return r;
}

RA2floatD max(const float& a, const RA2floatD& b) {
  RA2floatD r;
  #include "RA2maxPA.ipp"
  return r;
}

RA2floatD max(const double& a, const RA2floatS& b) {
  RA2floatD r;
  #include "RA2maxPA.ipp"
  return r;
}

RA2floatD max(const double& a, const RA2floatD& b) {
  RA2floatD r;
  #include "RA2maxPA.ipp"
  return r;
}

