// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RA2pow.hpp"

RA2floatD pow(const RA2floatD& a, const RA2floatD& b) {
  RA2floatD r;
  #include "RA2powAA.ipp"
  return r;
}

RA2floatD pow(const RA2floatD& a, const double& b) {
  RA2floatD r;
  double recip;
  RA2floatD s;
  RA2floatD t;
  int j;
  float expDiff;
  #include "RA2powAP.ipp"
  return r;
}

RA2floatD pow(const double& a, const RA2floatD& b) {
  RA2floatD r;
  #include "RA2powPA.ipp"
  return r;
}

