// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA2pow_INCLUDE_
#define _RA2pow_INCLUDE_
  #include "RA2prec.hpp"
  #include "RA2types.hpp"
  #include "RA2mult.hpp"
  #include "RA2log.hpp"
  #include "RA2exp.hpp"
  RA2floatD pow(const RA2floatD& a, const RA2floatD& b);
  RA2floatD pow(const RA2floatD& a, const double& b);
  RA2floatD pow(const double& a, const RA2floatD& b);
#endif
