// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
if (direction < 1 || direction > 28)
  {std::cerr << "RE1: Rapsodia set called with an out-of-bounds [1,28] direction"; exit(-1);}
if (degree < 1 || degree > 2)
  {std::cerr << "RE2: Rapsodia set called with an out-of-bounds [1,2] order"; exit(-1);}
switch(direction) {
  case 1:
    switch(degree) {
      case 1:
        (*this).d1_1 = passive;
        break;
      case 2:
        (*this).d1_2 = passive;
        break;
    }
    break;
  case 2:
    switch(degree) {
      case 1:
        (*this).d2_1 = passive;
        break;
      case 2:
        (*this).d2_2 = passive;
        break;
    }
    break;
  case 3:
    switch(degree) {
      case 1:
        (*this).d3_1 = passive;
        break;
      case 2:
        (*this).d3_2 = passive;
        break;
    }
    break;
  case 4:
    switch(degree) {
      case 1:
        (*this).d4_1 = passive;
        break;
      case 2:
        (*this).d4_2 = passive;
        break;
    }
    break;
  case 5:
    switch(degree) {
      case 1:
        (*this).d5_1 = passive;
        break;
      case 2:
        (*this).d5_2 = passive;
        break;
    }
    break;
  case 6:
    switch(degree) {
      case 1:
        (*this).d6_1 = passive;
        break;
      case 2:
        (*this).d6_2 = passive;
        break;
    }
    break;
  case 7:
    switch(degree) {
      case 1:
        (*this).d7_1 = passive;
        break;
      case 2:
        (*this).d7_2 = passive;
        break;
    }
    break;
  case 8:
    switch(degree) {
      case 1:
        (*this).d8_1 = passive;
        break;
      case 2:
        (*this).d8_2 = passive;
        break;
    }
    break;
  case 9:
    switch(degree) {
      case 1:
        (*this).d9_1 = passive;
        break;
      case 2:
        (*this).d9_2 = passive;
        break;
    }
    break;
  case 10:
    switch(degree) {
      case 1:
        (*this).d10_1 = passive;
        break;
      case 2:
        (*this).d10_2 = passive;
        break;
    }
    break;
  case 11:
    switch(degree) {
      case 1:
        (*this).d11_1 = passive;
        break;
      case 2:
        (*this).d11_2 = passive;
        break;
    }
    break;
  case 12:
    switch(degree) {
      case 1:
        (*this).d12_1 = passive;
        break;
      case 2:
        (*this).d12_2 = passive;
        break;
    }
    break;
  case 13:
    switch(degree) {
      case 1:
        (*this).d13_1 = passive;
        break;
      case 2:
        (*this).d13_2 = passive;
        break;
    }
    break;
  case 14:
    switch(degree) {
      case 1:
        (*this).d14_1 = passive;
        break;
      case 2:
        (*this).d14_2 = passive;
        break;
    }
    break;
  case 15:
    switch(degree) {
      case 1:
        (*this).d15_1 = passive;
        break;
      case 2:
        (*this).d15_2 = passive;
        break;
    }
    break;
  case 16:
    switch(degree) {
      case 1:
        (*this).d16_1 = passive;
        break;
      case 2:
        (*this).d16_2 = passive;
        break;
    }
    break;
  case 17:
    switch(degree) {
      case 1:
        (*this).d17_1 = passive;
        break;
      case 2:
        (*this).d17_2 = passive;
        break;
    }
    break;
  case 18:
    switch(degree) {
      case 1:
        (*this).d18_1 = passive;
        break;
      case 2:
        (*this).d18_2 = passive;
        break;
    }
    break;
  case 19:
    switch(degree) {
      case 1:
        (*this).d19_1 = passive;
        break;
      case 2:
        (*this).d19_2 = passive;
        break;
    }
    break;
  case 20:
    switch(degree) {
      case 1:
        (*this).d20_1 = passive;
        break;
      case 2:
        (*this).d20_2 = passive;
        break;
    }
    break;
  case 21:
    switch(degree) {
      case 1:
        (*this).d21_1 = passive;
        break;
      case 2:
        (*this).d21_2 = passive;
        break;
    }
    break;
  case 22:
    switch(degree) {
      case 1:
        (*this).d22_1 = passive;
        break;
      case 2:
        (*this).d22_2 = passive;
        break;
    }
    break;
  case 23:
    switch(degree) {
      case 1:
        (*this).d23_1 = passive;
        break;
      case 2:
        (*this).d23_2 = passive;
        break;
    }
    break;
  case 24:
    switch(degree) {
      case 1:
        (*this).d24_1 = passive;
        break;
      case 2:
        (*this).d24_2 = passive;
        break;
    }
    break;
  case 25:
    switch(degree) {
      case 1:
        (*this).d25_1 = passive;
        break;
      case 2:
        (*this).d25_2 = passive;
        break;
    }
    break;
  case 26:
    switch(degree) {
      case 1:
        (*this).d26_1 = passive;
        break;
      case 2:
        (*this).d26_2 = passive;
        break;
    }
    break;
  case 27:
    switch(degree) {
      case 1:
        (*this).d27_1 = passive;
        break;
      case 2:
        (*this).d27_2 = passive;
        break;
    }
    break;
  case 28:
    switch(degree) {
      case 1:
        (*this).d28_1 = passive;
        break;
      case 2:
        (*this).d28_2 = passive;
        break;
    }
    break;
}
