// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA2sinh_INCLUDE_
#define _RA2sinh_INCLUDE_
  #include "RA2prec.hpp"
  #include "RA2types.hpp"
  RA2floatS sinh(const RA2floatS& a);
  RA2floatD sinh(const RA2floatD& a);
#endif
