// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA2sin_INCLUDE_
#define _RA2sin_INCLUDE_
  #include "RA2prec.hpp"
  #include "RA2types.hpp"
  RA2floatS sin(const RA2floatS& a);
  RA2floatD sin(const RA2floatD& a);
#endif
