// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RA2sqrt.hpp"

RA2floatS sqrt(const RA2floatS& a) {
  RA2floatS r;
  float recip;
  #include "RA2sqrt.ipp"
  return r;
}

RA2floatD sqrt(const RA2floatD& a) {
  RA2floatD r;
  double recip;
  #include "RA2sqrt.ipp"
  return r;
}

