// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RA2tan.hpp"

RA2floatS tan(const RA2floatS& a) {
  RA2floatS r;
  #include "RA2tan.ipp"
  return r;
}

RA2floatD tan(const RA2floatD& a) {
  RA2floatD r;
  #include "RA2tan.ipp"
  return r;
}

