// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA2tan_INCLUDE_
#define _RA2tan_INCLUDE_
  #include "RA2prec.hpp"
  #include "RA2types.hpp"
  #include "RA2div.hpp"
  #include "RA2sin.hpp"
  #include "RA2cos.hpp"
  RA2floatS tan(const RA2floatS& a);
  RA2floatD tan(const RA2floatD& a);
#endif
