// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RA2uminus.hpp"

RA2floatS operator -(const RA2floatS& a) {
  RA2floatS r;
  #include "RA2uminus.ipp"
  return r;
}

RA2floatD operator -(const RA2floatD& a) {
  RA2floatD r;
  #include "RA2uminus.ipp"
  return r;
}

