// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA2uminus_INCLUDE_
#define _RA2uminus_INCLUDE_
  #include "RA2prec.hpp"
  #include "RA2types.hpp"
  RA2floatS operator -(const RA2floatS& a);
  RA2floatD operator -(const RA2floatD& a);
#endif
