// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA1atan_INCLUDE_
#define _RA1atan_INCLUDE_
  #include "RA1prec.hpp"
  #include "RA1types.hpp"
  #include "RA1add.hpp"
  #include "RA1div.hpp"
  #include "RA1mult.hpp"
  RA1floatS atan(const RA1floatS& a);
  RA1floatD atan(const RA1floatD& a);
#endif
