// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
factor_0 = 0.0;
if (a.v != 0.0)
  {
    if (a.v < 0.0)
      {
        factor_0 = -1.0;
      }
    else
      {
        factor_0 = 1.0;
      }
  }
r.v = fabs(a.v);
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d1_1 != 0.0)
      {
        if (a.d1_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d1_1 = a.d1_1 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d2_1 != 0.0)
      {
        if (a.d2_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d2_1 = a.d2_1 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d3_1 != 0.0)
      {
        if (a.d3_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d3_1 = a.d3_1 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d4_1 != 0.0)
      {
        if (a.d4_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d4_1 = a.d4_1 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d5_1 != 0.0)
      {
        if (a.d5_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d5_1 = a.d5_1 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d6_1 != 0.0)
      {
        if (a.d6_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d6_1 = a.d6_1 * factor_d;
factor_d = factor_0;
if (factor_d == 0.0)
  {
    if (a.d7_1 != 0.0)
      {
        if (a.d7_1 < 0.0)
          {
            factor_d = -1.0;
          }
        else
          {
            factor_d = 1.0;
          }
      }
  }
r.d7_1 = a.d7_1 * factor_d;
