// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RA1atan.hpp"

RA1floatS atan(const RA1floatS& a) {
  RA1floatS r;
  RA1floatS y;
  RA1floatS s;
  float one;
  #include "RA1atan.ipp"
  return r;
}

RA1floatD atan(const RA1floatD& a) {
  RA1floatD r;
  RA1floatD y;
  RA1floatD s;
  double one;
  #include "RA1atan.ipp"
  return r;
}

