// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
l.v = r.v;
l.d1_1 = r.d1_1;
l.d2_1 = r.d2_1;
l.d3_1 = r.d3_1;
l.d4_1 = r.d4_1;
l.d5_1 = r.d5_1;
l.d6_1 = r.d6_1;
l.d7_1 = r.d7_1;
