// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RA1acos.hpp"

RA1floatS acos(const RA1floatS& a) {
  RA1floatS r;
  RA1floatS h;
  RA1floatS t;
  #include "RA1acos.ipp"
  return r;
}

RA1floatD acos(const RA1floatD& a) {
  RA1floatD r;
  RA1floatD h;
  RA1floatD t;
  #include "RA1acos.ipp"
  return r;
}

