// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RA1abs.hpp"

RA1floatS fabs(const RA1floatS& a) {
  RA1floatS r;
  float factor_0;
  float factor_d;
  #include "RA1abs.ipp"
  return r;
}

RA1floatD fabs(const RA1floatD& a) {
  RA1floatD r;
  double factor_0;
  double factor_d;
  #include "RA1abs.ipp"
  return r;
}

