// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA1acos_INCLUDE_
#define _RA1acos_INCLUDE_
  #include "RA1prec.hpp"
  #include "RA1types.hpp"
  #include "RA1sqrt.hpp"
  #include "RA1div.hpp"
  #include "RA1mult.hpp"
  #include "RA1sub.hpp"
  #include "RA1uminus.hpp"
  RA1floatS acos(const RA1floatS& a);
  RA1floatD acos(const RA1floatD& a);
#endif
