// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA1abs_INCLUDE_
#define _RA1abs_INCLUDE_
  #include "RA1prec.hpp"
  #include "RA1types.hpp"
  RA1floatS fabs(const RA1floatS& a);
  RA1floatD fabs(const RA1floatD& a);
#endif
