// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RA1cosh.hpp"

RA1floatS cosh(const RA1floatS& a) {
  RA1floatS c;
  RA1floatS s;
  RA1floatS t;
  #include "RA1sinhcosh.ipp"
  return c;
}

RA1floatD cosh(const RA1floatD& a) {
  RA1floatD c;
  RA1floatD s;
  RA1floatD t;
  #include "RA1sinhcosh.ipp"
  return c;
}

