// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA1cosh_INCLUDE_
#define _RA1cosh_INCLUDE_
  #include "RA1prec.hpp"
  #include "RA1types.hpp"
  RA1floatS cosh(const RA1floatS& a);
  RA1floatD cosh(const RA1floatD& a);
#endif
