// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA1cos_INCLUDE_
#define _RA1cos_INCLUDE_
  #include "RA1prec.hpp"
  #include "RA1types.hpp"
  RA1floatS cos(const RA1floatS& a);
  RA1floatD cos(const RA1floatD& a);
#endif
