// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
r.v = a / b.v;
r.d1_1 = r.v * (-r.v * b.d1_1);
r.d2_1 = r.v * (-r.v * b.d2_1);
r.d3_1 = r.v * (-r.v * b.d3_1);
r.d4_1 = r.v * (-r.v * b.d4_1);
r.d5_1 = r.v * (-r.v * b.d5_1);
r.d6_1 = r.v * (-r.v * b.d6_1);
r.d7_1 = r.v * (-r.v * b.d7_1);
