// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
r.v = a.v / b;
r.d1_1 = a.d1_1 / b;
r.d2_1 = a.d2_1 / b;
r.d3_1 = a.d3_1 / b;
r.d4_1 = a.d4_1 / b;
r.d5_1 = a.d5_1 / b;
r.d6_1 = a.d6_1 / b;
r.d7_1 = a.d7_1 / b;
