// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RA1eqadd.hpp"

void operator +=(RA1floatS& r, const RA1floatS& b) {
  #include "RA1eqaddAA.ipp"
}

void operator +=(RA1floatD& r, const RA1floatS& b) {
  #include "RA1eqaddAA.ipp"
}

void operator +=(RA1floatD& r, const RA1floatD& b) {
  #include "RA1eqaddAA.ipp"
}

void operator +=(RA1floatS& r, const int& b) {
  #include "RA1eqaddAP.ipp"
}

void operator +=(RA1floatS& r, const float& b) {
  #include "RA1eqaddAP.ipp"
}

void operator +=(RA1floatD& r, const int& b) {
  #include "RA1eqaddAP.ipp"
}

void operator +=(RA1floatD& r, const float& b) {
  #include "RA1eqaddAP.ipp"
}

void operator +=(RA1floatD& r, const double& b) {
  #include "RA1eqaddAP.ipp"
}

