// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA1eqdiv_INCLUDE_
#define _RA1eqdiv_INCLUDE_
  #include "RA1prec.hpp"
  #include "RA1types.hpp"
  #include "RA1div.hpp"
  void operator /=(RA1floatS& r, const RA1floatS& b);
  void operator /=(RA1floatD& r, const RA1floatS& b);
  void operator /=(RA1floatD& r, const RA1floatD& b);
  void operator /=(RA1floatS& r, const int& b);
  void operator /=(RA1floatS& r, const float& b);
  void operator /=(RA1floatD& r, const int& b);
  void operator /=(RA1floatD& r, const float& b);
  void operator /=(RA1floatD& r, const double& b);
#endif
