// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA1exp_INCLUDE_
#define _RA1exp_INCLUDE_
  #include "RA1prec.hpp"
  #include "RA1types.hpp"
  RA1floatS exp(const RA1floatS& a);
  RA1floatD exp(const RA1floatD& a);
#endif
