// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
recip = 1.0 / b.v;
r.v = a.v * recip;
r.d1_1 = recip * (a.d1_1 - (r.v * b.d1_1));
r.d2_1 = recip * (a.d2_1 - (r.v * b.d2_1));
r.d3_1 = recip * (a.d3_1 - (r.v * b.d3_1));
r.d4_1 = recip * (a.d4_1 - (r.v * b.d4_1));
r.d5_1 = recip * (a.d5_1 - (r.v * b.d5_1));
r.d6_1 = recip * (a.d6_1 - (r.v * b.d6_1));
r.d7_1 = recip * (a.d7_1 - (r.v * b.d7_1));
