// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RA1exp.hpp"

RA1floatS exp(const RA1floatS& a) {
  RA1floatS r;
  RA1floatS s;
  RA1floatS t;
  #include "RA1exp.ipp"
  return r;
}

RA1floatD exp(const RA1floatD& a) {
  RA1floatD r;
  RA1floatD s;
  RA1floatD t;
  #include "RA1exp.ipp"
  return r;
}

