// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
r.d1_1 = r.v * b.d1_1 + r.d1_1 * b.v;
r.d2_1 = r.v * b.d2_1 + r.d2_1 * b.v;
r.d3_1 = r.v * b.d3_1 + r.d3_1 * b.v;
r.d4_1 = r.v * b.d4_1 + r.d4_1 * b.v;
r.d5_1 = r.v * b.d5_1 + r.d5_1 * b.v;
r.d6_1 = r.v * b.d6_1 + r.d6_1 * b.v;
r.d7_1 = r.v * b.d7_1 + r.d7_1 * b.v;
r.v = r.v * b.v;
