// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RA1eqdiv.hpp"

void operator /=(RA1floatS& r, const RA1floatS& b) {
  RA1floatS a = r;
  float recip;
  #include "RA1eqdivAA.ipp"
}

void operator /=(RA1floatD& r, const RA1floatS& b) {
  RA1floatD a = r;
  double recip;
  #include "RA1eqdivAA.ipp"
}

void operator /=(RA1floatD& r, const RA1floatD& b) {
  RA1floatD a = r;
  double recip;
  #include "RA1eqdivAA.ipp"
}

void operator /=(RA1floatS& r, const int& b) {
  RA1floatS a = r;
  float recip;
  #include "RA1eqdivAP.ipp"
}

void operator /=(RA1floatS& r, const float& b) {
  RA1floatS a = r;
  float recip;
  #include "RA1eqdivAP.ipp"
}

void operator /=(RA1floatD& r, const int& b) {
  RA1floatD a = r;
  double recip;
  #include "RA1eqdivAP.ipp"
}

void operator /=(RA1floatD& r, const float& b) {
  RA1floatD a = r;
  double recip;
  #include "RA1eqdivAP.ipp"
}

void operator /=(RA1floatD& r, const double& b) {
  RA1floatD a = r;
  double recip;
  #include "RA1eqdivAP.ipp"
}

