// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
r.v = r.v + b;
r.d1_1 = r.d1_1;
r.d2_1 = r.d2_1;
r.d3_1 = r.d3_1;
r.d4_1 = r.d4_1;
r.d5_1 = r.d5_1;
r.d6_1 = r.d6_1;
r.d7_1 = r.d7_1;
