// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
r.v = exp(a.v);
// scale input
s.d1_1 = 1 * a.d1_1;
// compute output
t.d1_1 = r.v * s.d1_1;
r.d1_1 = t.d1_1 / 1.0;
// scale input
s.d2_1 = 1 * a.d2_1;
// compute output
t.d2_1 = r.v * s.d2_1;
r.d2_1 = t.d2_1 / 1.0;
// scale input
s.d3_1 = 1 * a.d3_1;
// compute output
t.d3_1 = r.v * s.d3_1;
r.d3_1 = t.d3_1 / 1.0;
// scale input
s.d4_1 = 1 * a.d4_1;
// compute output
t.d4_1 = r.v * s.d4_1;
r.d4_1 = t.d4_1 / 1.0;
// scale input
s.d5_1 = 1 * a.d5_1;
// compute output
t.d5_1 = r.v * s.d5_1;
r.d5_1 = t.d5_1 / 1.0;
// scale input
s.d6_1 = 1 * a.d6_1;
// compute output
t.d6_1 = r.v * s.d6_1;
r.d6_1 = t.d6_1 / 1.0;
// scale input
s.d7_1 = 1 * a.d7_1;
// compute output
t.d7_1 = r.v * s.d7_1;
r.d7_1 = t.d7_1 / 1.0;
