// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
if (direction < 1 || direction > 7)
  {std::cerr << "RE1: Rapsodia get called with an out-of-bounds [1,7] direction"; exit(-1);}
if (degree < 1 || degree > 1)
  {std::cerr << "RE2: Rapsodia get called with an out-of-bounds [1,1] order"; exit(-1);}
switch(direction) {
  case 1:
    switch(degree) {
      case 1:
        passive = (*this).d1_1;
        break;
    }
    break;
  case 2:
    switch(degree) {
      case 1:
        passive = (*this).d2_1;
        break;
    }
    break;
  case 3:
    switch(degree) {
      case 1:
        passive = (*this).d3_1;
        break;
    }
    break;
  case 4:
    switch(degree) {
      case 1:
        passive = (*this).d4_1;
        break;
    }
    break;
  case 5:
    switch(degree) {
      case 1:
        passive = (*this).d5_1;
        break;
    }
    break;
  case 6:
    switch(degree) {
      case 1:
        passive = (*this).d6_1;
        break;
    }
    break;
  case 7:
    switch(degree) {
      case 1:
        passive = (*this).d7_1;
        break;
    }
    break;
}
