// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA1lt_INCLUDE_
#define _RA1lt_INCLUDE_
  #include "RA1prec.hpp"
  #include "RA1types.hpp"
  bool operator <(const RA1floatS& a, const RA1floatS& b);
  bool operator <(const RA1floatS& a, const RA1floatD& b);
  bool operator <(const RA1floatD& a, const RA1floatS& b);
  bool operator <(const RA1floatD& a, const RA1floatD& b);
  bool operator <(const RA1floatS& a, const int& b);
  bool operator <(const RA1floatS& a, const float& b);
  bool operator <(const RA1floatS& a, const double& b);
  bool operator <(const RA1floatD& a, const int& b);
  bool operator <(const RA1floatD& a, const float& b);
  bool operator <(const RA1floatD& a, const double& b);
  bool operator <(const int& a, const RA1floatS& b);
  bool operator <(const int& a, const RA1floatD& b);
  bool operator <(const float& a, const RA1floatS& b);
  bool operator <(const float& a, const RA1floatD& b);
  bool operator <(const double& a, const RA1floatS& b);
  bool operator <(const double& a, const RA1floatD& b);
#endif
