// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RA1lt.hpp"

bool operator <(const RA1floatS& a, const RA1floatS& b) {
  bool r;
  #include "RA1ltAA.ipp"
  return r;
}

bool operator <(const RA1floatS& a, const RA1floatD& b) {
  bool r;
  #include "RA1ltAA.ipp"
  return r;
}

bool operator <(const RA1floatD& a, const RA1floatS& b) {
  bool r;
  #include "RA1ltAA.ipp"
  return r;
}

bool operator <(const RA1floatD& a, const RA1floatD& b) {
  bool r;
  #include "RA1ltAA.ipp"
  return r;
}

bool operator <(const RA1floatS& a, const int& b) {
  bool r;
  #include "RA1ltAP.ipp"
  return r;
}

bool operator <(const RA1floatS& a, const float& b) {
  bool r;
  #include "RA1ltAP.ipp"
  return r;
}

bool operator <(const RA1floatS& a, const double& b) {
  bool r;
  #include "RA1ltAP.ipp"
  return r;
}

bool operator <(const RA1floatD& a, const int& b) {
  bool r;
  #include "RA1ltAP.ipp"
  return r;
}

bool operator <(const RA1floatD& a, const float& b) {
  bool r;
  #include "RA1ltAP.ipp"
  return r;
}

bool operator <(const RA1floatD& a, const double& b) {
  bool r;
  #include "RA1ltAP.ipp"
  return r;
}

bool operator <(const int& a, const RA1floatS& b) {
  bool r;
  #include "RA1ltPA.ipp"
  return r;
}

bool operator <(const int& a, const RA1floatD& b) {
  bool r;
  #include "RA1ltPA.ipp"
  return r;
}

bool operator <(const float& a, const RA1floatS& b) {
  bool r;
  #include "RA1ltPA.ipp"
  return r;
}

bool operator <(const float& a, const RA1floatD& b) {
  bool r;
  #include "RA1ltPA.ipp"
  return r;
}

bool operator <(const double& a, const RA1floatS& b) {
  bool r;
  #include "RA1ltPA.ipp"
  return r;
}

bool operator <(const double& a, const RA1floatD& b) {
  bool r;
  #include "RA1ltPA.ipp"
  return r;
}

