// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RA1log.hpp"

RA1floatS log(const RA1floatS& a) {
  RA1floatS r;
  RA1floatS s;
  RA1floatS t;
  float recip;
  #include "RA1log.ipp"
  return r;
}

RA1floatD log(const RA1floatD& a) {
  RA1floatD r;
  RA1floatD s;
  RA1floatD t;
  double recip;
  #include "RA1log.ipp"
  return r;
}

