// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA1log_INCLUDE_
#define _RA1log_INCLUDE_
  #include "RA1prec.hpp"
  #include "RA1types.hpp"
  RA1floatS log(const RA1floatS& a);
  RA1floatD log(const RA1floatD& a);
#endif
