// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RA1max.hpp"

RA1floatS max(const RA1floatS& a, const RA1floatS& b) {
  RA1floatS r;
  #include "RA1maxAA.ipp"
  return r;
}

RA1floatD max(const RA1floatS& a, const RA1floatD& b) {
  RA1floatD r;
  #include "RA1maxAA.ipp"
  return r;
}

RA1floatD max(const RA1floatD& a, const RA1floatS& b) {
  RA1floatD r;
  #include "RA1maxAA.ipp"
  return r;
}

RA1floatD max(const RA1floatD& a, const RA1floatD& b) {
  RA1floatD r;
  #include "RA1maxAA.ipp"
  return r;
}

RA1floatS max(const RA1floatS& a, const int& b) {
  RA1floatS r;
  #include "RA1maxAP.ipp"
  return r;
}

RA1floatS max(const RA1floatS& a, const float& b) {
  RA1floatS r;
  #include "RA1maxAP.ipp"
  return r;
}

RA1floatD max(const RA1floatS& a, const double& b) {
  RA1floatD r;
  #include "RA1maxAP.ipp"
  return r;
}

RA1floatD max(const RA1floatD& a, const int& b) {
  RA1floatD r;
  #include "RA1maxAP.ipp"
  return r;
}

RA1floatD max(const RA1floatD& a, const float& b) {
  RA1floatD r;
  #include "RA1maxAP.ipp"
  return r;
}

RA1floatD max(const RA1floatD& a, const double& b) {
  RA1floatD r;
  #include "RA1maxAP.ipp"
  return r;
}

RA1floatS max(const int& a, const RA1floatS& b) {
  RA1floatS r;
  #include "RA1maxPA.ipp"
  return r;
}

RA1floatD max(const int& a, const RA1floatD& b) {
  RA1floatD r;
  #include "RA1maxPA.ipp"
  return r;
}

RA1floatS max(const float& a, const RA1floatS& b) {
  RA1floatS r;
  #include "RA1maxPA.ipp"
  return r;
}

RA1floatD max(const float& a, const RA1floatD& b) {
  RA1floatD r;
  #include "RA1maxPA.ipp"
  return r;
}

RA1floatD max(const double& a, const RA1floatS& b) {
  RA1floatD r;
  #include "RA1maxPA.ipp"
  return r;
}

RA1floatD max(const double& a, const RA1floatD& b) {
  RA1floatD r;
  #include "RA1maxPA.ipp"
  return r;
}

