// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA1min_INCLUDE_
#define _RA1min_INCLUDE_
  #include "RA1prec.hpp"
  #include "RA1types.hpp"
  RA1floatS min(const RA1floatS& a, const RA1floatS& b);
  RA1floatD min(const RA1floatS& a, const RA1floatD& b);
  RA1floatD min(const RA1floatD& a, const RA1floatS& b);
  RA1floatD min(const RA1floatD& a, const RA1floatD& b);
  RA1floatS min(const RA1floatS& a, const int& b);
  RA1floatS min(const RA1floatS& a, const float& b);
  RA1floatD min(const RA1floatS& a, const double& b);
  RA1floatD min(const RA1floatD& a, const int& b);
  RA1floatD min(const RA1floatD& a, const float& b);
  RA1floatD min(const RA1floatD& a, const double& b);
  RA1floatS min(const int& a, const RA1floatS& b);
  RA1floatD min(const int& a, const RA1floatD& b);
  RA1floatS min(const float& a, const RA1floatS& b);
  RA1floatD min(const float& a, const RA1floatD& b);
  RA1floatD min(const double& a, const RA1floatS& b);
  RA1floatD min(const double& a, const RA1floatD& b);
#endif
