// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
if (a.v < b)
  {
    r.v = b;
    r.d1_1 = 0;
    r.d2_1 = 0;
    r.d3_1 = 0;
    r.d4_1 = 0;
    r.d5_1 = 0;
    r.d6_1 = 0;
    r.d7_1 = 0;
  }
else
  {
    r.v = a.v;
    r.d1_1 = a.d1_1;
    r.d2_1 = a.d2_1;
    r.d3_1 = a.d3_1;
    r.d4_1 = a.d4_1;
    r.d5_1 = a.d5_1;
    r.d6_1 = a.d6_1;
    r.d7_1 = a.d7_1;
  }
