// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RA1min.hpp"

RA1floatS min(const RA1floatS& a, const RA1floatS& b) {
  RA1floatS r;
  #include "RA1minAA.ipp"
  return r;
}

RA1floatD min(const RA1floatS& a, const RA1floatD& b) {
  RA1floatD r;
  #include "RA1minAA.ipp"
  return r;
}

RA1floatD min(const RA1floatD& a, const RA1floatS& b) {
  RA1floatD r;
  #include "RA1minAA.ipp"
  return r;
}

RA1floatD min(const RA1floatD& a, const RA1floatD& b) {
  RA1floatD r;
  #include "RA1minAA.ipp"
  return r;
}

RA1floatS min(const RA1floatS& a, const int& b) {
  RA1floatS r;
  #include "RA1minAP.ipp"
  return r;
}

RA1floatS min(const RA1floatS& a, const float& b) {
  RA1floatS r;
  #include "RA1minAP.ipp"
  return r;
}

RA1floatD min(const RA1floatS& a, const double& b) {
  RA1floatD r;
  #include "RA1minAP.ipp"
  return r;
}

RA1floatD min(const RA1floatD& a, const int& b) {
  RA1floatD r;
  #include "RA1minAP.ipp"
  return r;
}

RA1floatD min(const RA1floatD& a, const float& b) {
  RA1floatD r;
  #include "RA1minAP.ipp"
  return r;
}

RA1floatD min(const RA1floatD& a, const double& b) {
  RA1floatD r;
  #include "RA1minAP.ipp"
  return r;
}

RA1floatS min(const int& a, const RA1floatS& b) {
  RA1floatS r;
  #include "RA1minPA.ipp"
  return r;
}

RA1floatD min(const int& a, const RA1floatD& b) {
  RA1floatD r;
  #include "RA1minPA.ipp"
  return r;
}

RA1floatS min(const float& a, const RA1floatS& b) {
  RA1floatS r;
  #include "RA1minPA.ipp"
  return r;
}

RA1floatD min(const float& a, const RA1floatD& b) {
  RA1floatD r;
  #include "RA1minPA.ipp"
  return r;
}

RA1floatD min(const double& a, const RA1floatS& b) {
  RA1floatD r;
  #include "RA1minPA.ipp"
  return r;
}

RA1floatD min(const double& a, const RA1floatD& b) {
  RA1floatD r;
  #include "RA1minPA.ipp"
  return r;
}

