// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
r.v = b.v * a;
r.d1_1 = b.d1_1 * a;
r.d2_1 = b.d2_1 * a;
r.d3_1 = b.d3_1 * a;
r.d4_1 = b.d4_1 * a;
r.d5_1 = b.d5_1 * a;
r.d6_1 = b.d6_1 * a;
r.d7_1 = b.d7_1 * a;
