// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
r.v = a.v * b.v;
r.d1_1 = a.v * b.d1_1 + a.d1_1 * b.v;
r.d2_1 = a.v * b.d2_1 + a.d2_1 * b.v;
r.d3_1 = a.v * b.d3_1 + a.d3_1 * b.v;
r.d4_1 = a.v * b.d4_1 + a.d4_1 * b.v;
r.d5_1 = a.v * b.d5_1 + a.d5_1 * b.v;
r.d6_1 = a.v * b.d6_1 + a.d6_1 * b.v;
r.d7_1 = a.v * b.d7_1 + a.d7_1 * b.v;
