// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA1pow_INCLUDE_
#define _RA1pow_INCLUDE_
  #include "RA1prec.hpp"
  #include "RA1types.hpp"
  #include "RA1mult.hpp"
  #include "RA1log.hpp"
  #include "RA1exp.hpp"
  RA1floatD pow(const RA1floatD& a, const RA1floatD& b);
  RA1floatD pow(const RA1floatD& a, const double& b);
  RA1floatD pow(const double& a, const RA1floatD& b);
#endif
