// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RA1pow.hpp"

RA1floatD pow(const RA1floatD& a, const RA1floatD& b) {
  RA1floatD r;
  #include "RA1powAA.ipp"
  return r;
}

RA1floatD pow(const RA1floatD& a, const double& b) {
  RA1floatD r;
  double recip;
  RA1floatD s;
  RA1floatD t;
  int j;
  float expDiff;
  #include "RA1powAP.ipp"
  return r;
}

RA1floatD pow(const double& a, const RA1floatD& b) {
  RA1floatD r;
  #include "RA1powPA.ipp"
  return r;
}

