// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
r.v = sqrt(a.v);
recip = 0.5 / r.v;
r.d1_1 = recip * (a.d1_1);
r.d2_1 = recip * (a.d2_1);
r.d3_1 = recip * (a.d3_1);
r.d4_1 = recip * (a.d4_1);
r.d5_1 = recip * (a.d5_1);
r.d6_1 = recip * (a.d6_1);
r.d7_1 = recip * (a.d7_1);
