// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RA1sqrt.hpp"

RA1floatS sqrt(const RA1floatS& a) {
  RA1floatS r;
  float recip;
  #include "RA1sqrt.ipp"
  return r;
}

RA1floatD sqrt(const RA1floatD& a) {
  RA1floatD r;
  double recip;
  #include "RA1sqrt.ipp"
  return r;
}

