// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
r.v = a - b.v;
r.d1_1 = -b.d1_1;
r.d2_1 = -b.d2_1;
r.d3_1 = -b.d3_1;
r.d4_1 = -b.d4_1;
r.d5_1 = -b.d5_1;
r.d6_1 = -b.d6_1;
r.d7_1 = -b.d7_1;
