// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA1sinh_INCLUDE_
#define _RA1sinh_INCLUDE_
  #include "RA1prec.hpp"
  #include "RA1types.hpp"
  RA1floatS sinh(const RA1floatS& a);
  RA1floatD sinh(const RA1floatD& a);
#endif
