// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA1sqrt_INCLUDE_
#define _RA1sqrt_INCLUDE_
  #include "RA1prec.hpp"
  #include "RA1types.hpp"
  RA1floatS sqrt(const RA1floatS& a);
  RA1floatD sqrt(const RA1floatD& a);
#endif
