// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA1tan_INCLUDE_
#define _RA1tan_INCLUDE_
  #include "RA1prec.hpp"
  #include "RA1types.hpp"
  #include "RA1div.hpp"
  #include "RA1sin.hpp"
  #include "RA1cos.hpp"
  RA1floatS tan(const RA1floatS& a);
  RA1floatD tan(const RA1floatD& a);
#endif
