// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RA1tan.hpp"

RA1floatS tan(const RA1floatS& a) {
  RA1floatS r;
  #include "RA1tan.ipp"
  return r;
}

RA1floatD tan(const RA1floatD& a) {
  RA1floatD r;
  #include "RA1tan.ipp"
  return r;
}

