// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#ifndef _RA1uminus_INCLUDE_
#define _RA1uminus_INCLUDE_
  #include "RA1prec.hpp"
  #include "RA1types.hpp"
  RA1floatS operator -(const RA1floatS& a);
  RA1floatD operator -(const RA1floatD& a);
#endif
