// This file was generated by Rapsodia (see www.mcs.anl.gov/Rapsodia)
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "RA1uminus.hpp"

RA1floatS operator -(const RA1floatS& a) {
  RA1floatS r;
  #include "RA1uminus.ipp"
  return r;
}

RA1floatD operator -(const RA1floatD& a) {
  RA1floatD r;
  #include "RA1uminus.ipp"
  return r;
}

